/**
 * Report Generation
 * Creates Google Docs reports from analysis data.
 */

/**
 * Creates a daily analysis report.
 * @param {Object} data - Analysis data from Gemini
 * @param {string} userEmail - User's email
 * @returns {string} URL of the created document
 */
function createDailyReport(data, userEmail) {
  if (!data) throw new Error("No data provided for report");

  var dateStr = Utilities.formatDate(
    new Date(),
    Session.getScriptTimeZone(),
    "yyyy-MM-dd"
  );
  var docName = "Stock Analysis Report - " + dateStr;

  // Create blank document
  var doc = DocumentApp.create(docName);
  var body = doc.getBody();

  // Header
  var header = body.appendParagraph(
    "일일 주식 시장 분석 리포트 (Daily Stock Analysis)"
  );
  header.setHeading(DocumentApp.ParagraphHeading.HEADING1);
  header.setAlignment(DocumentApp.HorizontalAlignment.CENTER);

  body.appendParagraph("날짜 (Date): " + dateStr);
  body.appendParagraph("사용자 (User): " + userEmail);
  body.appendHorizontalRule();

  // Market Summary
  body
    .appendParagraph("시장 요약 (Market Summary)")
    .setHeading(DocumentApp.ParagraphHeading.HEADING2);
  body.appendParagraph(data.market_summary || "N/A");

  // Sentiment
  var sentimentPara = body.appendParagraph(
    "시장 심리 (Sentiment): " + (data.sentiment || "Neutral")
  );
  sentimentPara.setHeading(DocumentApp.ParagraphHeading.HEADING3);

  // Key Events
  if (data.key_events && data.key_events.length > 0) {
    body
      .appendParagraph("주요 이벤트 (Key Events)")
      .setHeading(DocumentApp.ParagraphHeading.HEADING2);
    data.key_events.forEach(function (event) {
      body.appendListItem(event);
    });
  }

  // Investment Insight
  body
    .appendParagraph("투자 인사이트 (Investment Insight)")
    .setHeading(DocumentApp.ParagraphHeading.HEADING2);
  body.appendParagraph(data.investment_insight || "N/A");

  // Footer
  body.appendHorizontalRule();
  body
    .appendParagraph(
      "Disclaimer: 이 리포트는 AI에 의해 생성되었으며 투자 조언이 아닙니다. (This report is generated by AI.)"
    )
    .setAttributes({
      ITALIC: true,
      FONT_SIZE: 8,
    });

  doc.saveAndClose();

  // Optionally move to a specific folder or share
  // var file = DriveApp.getFileById(doc.getId());
  // file.addViewer(userEmail);

  return doc.getUrl();
}
